matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

language: cpp

before_install:
  - travis_retry sudo apt-get update -qq
  
install:
  - travis_retry sudo apt-get install scons

script:
  - scons target=all -j24
  - ./main.exe
