matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

language: cpp

before_install:
  - travis_retry sudo apt-get update -qq
  
install:
  - travis_retry sudo apt-get install lcov

script:
  - mkdir build 
  - cd build 
  - cmake .. -DT=all 
  - make -j24
  - cd ..
  - InitialCoverage.sh
  - ./build/main.exe
  - ReportCoverage.sh
