os: linux
language: python
python: "3.7"
dist: xenial
compiler:
  - gcc
install:
# Install conan
  - pip install conan
# Automatic detection of your arch, compiler, etc.
  - conan user
script:
# Download dependencies and build project
  - conan install .
# Call your build system and run
  - mkdir build 
  - cd build 
  - cmake .. -DT=all 
  - make -j24
  - cd ..
  - InitialCoverage.sh
  - ./build/main.exe
  - ReportCoverage.sh
