# Appveyor configuration file for CI build of hiredis on Windows (under Cygwin)
environment:
    matrix:
        - CC: gcc

image:
  - Ubuntu
  
clone_depth: 1
# Attempt to ensure we don't try to convert line endings to Win32 CRLF as this will cause build to fail
init:
    - git config --global core.autocrlf input

build_script:
    - 'echo building...'
    - 'bash -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; mkdir build && cd build && cmake .. && make VERBOSE=1"'

test_script:
  - 'main.exe'
