Import('env')
import os

src_files = []
if env['BUILD_TARGET'] != 'all':
    src_files.append( Glob(os.path.join('.', '%s_test.cpp' % env['BUILD_TARGET'])) )
    src_files.append( Glob(os.path.join('.', 'main.cpp')) )
else:
    src_files.append( Glob(os.path.join('.', '*.cpp')) )

Return ('src_files')
