Import('env')
import os

env.Append(CPPPATH = [os.path.join(Dir('.').srcnode().abspath, 'include')] )

src_files = []
src_files.append( Glob(os.path.join('.', 'src', '*.cpp')) )
src_files.append( Glob(os.path.join('.', 'src', '*.c')) )

Return ('src_files')
