Import('env')
import os

supportLibs = [
    'gtest',
    'panic',
    'common',
]

src_files = []

# Add libs.
for lib in supportLibs:
    src_files.append(SConscript(os.path.join('libs', lib, 'SConscript'), {'env': env}))

# Add source code.
src_files.append(SConscript(os.path.join('code', 'SConscript'), {'env': env}))

# Add testcase.
src_files.append(SConscript(os.path.join('testcase', 'SConscript'), {'env': env}))

Return ('src_files')
